<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE biblioteca [
<!ELEMENT biblioteca (libro)+>
<!ELEMENT libro (autor,titulo)>
<!ATTLIST libro codigo CDATA #REQUIRED>
<!ATTLIST libro ubicacion CDATA #IMPLIED>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
]>


<biblioteca>
  <libro codigo="123" ubicacion="estantería 1">
    <autor>Miguel de Cervantes Saavedra</autor>
    <titulo>El Quijote de la Mancha</titulo>
  </libro>
  <libro codigo="1023" ubicacion="estantería 3">
    <autor>Pablo Neruda</autor>
    <titulo>Veinte poemas de amor y una canción desesperada</titulo>
  </libro>
</biblioteca>