<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE factura [
<!ELEMENT factura (emision,vendedor,cliente,articulo+,descuento)>
<!ATTLIST factura id CDATA #REQUIRED>
<!ELEMENT emision (#PCDATA)>
<!ELEMENT vendedor (nombre)>
<!ATTLIST vendedor id CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT cliente (nombre,direccion,telefono+)>
<!ATTLIST cliente id CDATA #REQUIRED>
<!ELEMENT direccion (via,cp,localidad,provincia)>
<!ELEMENT via (#PCDATA)>
<!ELEMENT cp (#PCDATA)>
<!ELEMENT localidad (#PCDATA)>
<!ELEMENT provincia (#PCDATA)>
<!ELEMENT telefono ANY>
<!ATTLIST telefono num CDATA #REQUIRED>
<!ELEMENT articulo (denominacion,precio,cantidad)>
<!ATTLIST articulo id CDATA #REQUIRED>
<!ATTLIST articulo iva CDATA #REQUIRED>
<!ELEMENT denominacion (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT cantidad (#PCDATA)>
<!ELEMENT descuento (#PCDATA)>
]>


<factura id="876">
  <emision>2012-02-28T08:25:02</emision>
  <vendedor id="12">
    <nombre>Felipe Cuesta Pérez</nombre>    
  </vendedor>
  <cliente id="9878">
    <nombre>Raquel Rengo Suárez</nombre>
    <direccion>
      <via>Calle Alonso Cano, 2, 3º A</via>
      <cp>41700</cp>
      <localidad>Dos Hermanas</localidad>
      <provincia>Sevilla</provincia>
    </direccion>
    <telefono num="666111666"/>
    <telefono num="954666111"/>
  </cliente>
  <articulo id="121" iva="18">
    <denominacion>Silla giratoria modelo C-121</denominacion>
    <precio>98.23</precio>
    <cantidad>1</cantidad>
  </articulo>
  <articulo id="9341" iva="18">
    <denominacion>Mesa estudio 120x80 haya modelo A2-456-X</denominacion>
    <precio>193.23</precio>
    <cantidad>1</cantidad>
  </articulo>
  <articulo id="1124" iva="18">
    <denominacion>Lámpara mesa con pantalla naranja modelo AK-987</denominacion>
    <precio>23.12</precio>
    <cantidad>2</cantidad>    
  </articulo>
  <descuento>20</descuento>
</factura>